# This is a basic workflow to help you get started with Actions

name: Angular-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Setup nodejs
      - name: Setup nodejs
        run: actions/setup-node@v3.7.0
        with:
            node-version: "18"

      # Install deps
      - name: Install deps
        run: npm i
        
      # Build app for production
      - name: Build app bundle
        run: npm run build:prod
        
      # Deploy to Github pages
      - name: Deploy to GH Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
